### ISSUE TITLE
Get Data From API Securely without user login

### ISSUE THREAD

**Issue by 72mahdii** [mmacneil/AngularASPNETCoreOAuth#1]
Hi Mark
Thanks for your article, it was quite helpful, I have a lot of questions about this approach, I hope you can help me if you wish to help a newbie  :)

First of all, **How can get data from the API in Angular securely without user login, you know, for example, when you want to show articles on the website without needing to user login for getting data from API.**

In following **How could log in with no need to go in the Identity Server app to log in, like sending a post request with login information in its body securely to Identity Server, I think its quite a drawback with those all going difference links, and  call-back component, it should be a simple login inside Angular like registration!**

I'll very grateful if you could help me in any sort of, articles, codes, examples, etc :)

**Comment by vobrechkov** [comment]
What you're asking, the way you are describing it, is not something typically done. If your articles are to be shown without requiring users to login - then why do you need to protect the API call with fictitious username and password? This sounds like public information that should not require authentication on the client or resource server (API).
