### ISSUE TITLE
sign out does not properly work

### ISSUE THREAD

**Issue by guyng** [mmacneil/AngularASPNETCoreOAuth#2]
Hi,
After i have logged in, once i click on sign out it redirect me to the home page but 
then when i press on log in it instantly authenticate me. 

I believe it is because the log out functionality isn't implemented in the server side(auth server).
Can you take a look?

**Comment by Michaelwan777** [comment]
It works for me. Probably you click the 'Remember me' when you first login.

**Comment by nkaenzig** [comment]
Doesn't work for me either. The signup() function doesn't delete the cookie. (I did not select 'Remember me' during the login

**Comment by Michaelwan777** [comment]
> Doesn't work for me either. The signup() function doesn't delete the cookie. (I did not select 'Remember me' during the login)

Yep, there's problem in delete cookie. It probably the bug in IdentityServer. Since there's only one method called in Signout.

**Comment by nkaenzig** [comment]
> > Doesn't work for me either. The signup() function doesn't delete the cookie. (I did not select 'Remember me' during the login)
> 
> Do you mean 'Sign out' instead of 'Sign up'? If so, yes, there's a problem in delete token cookie. Probably it's some unknown bugs in IdentityServer4. Since there's only one redirect method called in Signout. I'm also trying to fix this problem.

Yes I meant "Sign Out", thank you. It also seems to me that it's a bug in Identity Server. The signoutRedirect() in your code calls properly the End Session endpoint, with the id_token_hint and post_logout_redirect_uri parameters set (I checked that in Fiddler).

Did this also occur in earlier versions of Identity Server or do you know a version where it works?
Or maybe do you know of another way to solve this? (There has to be, as many pages use IdentityServer in production, and it's recommended by Microsoft...)

**Comment by nkaenzig** [comment]
Got it finally working. 
On the client side, the only thing you have to do is to call the signoutRedirect() function (of oicd-client-js), which is already done in this template. This will call the End Session Endpoint (connect/endsession) of IdentityServer, which by default will redirect you to the Account/Logout route, but only if such a route exists (which is not the case in this template). 
So you have to create a Logout() method in the AccountController.cs class, where you call the SignOutAsync() method, which will revoke the cookie, and then you can redirect back to the client.

```
[HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            await _signInManager.SignOutAsync();
            return Redirect("http//:localhost:4200");
        }
```
Instead of hardcoding the url of the client you can also use the PostLogoutRedirectUri that is passed by the client's call issued by signoutRedirect().
To access this parameter on the server, you can do the following:

`var context = await _interaction.GetLogoutContextAsync(logoutId);
 return Redirect(context.PostLogoutRedirectUri);
`
... where _interaction is a IIdentityServerInteractionService.

**Comment by itorian** [comment]
> Got it finally working.
> On the client side, the only thing you have to do is to call the signoutRedirect() function (of oicd-client-js), which is already done in this template. This will call the End Session Endpoint (connect/endsession) of IdentityServer, which by default will redirect you to the Account/Logout route, but only if such a route exists (which is not the case in this template).
> So you have to create a Logout() method in the AccountController.cs class, where you call the SignOutAsync() method, which will revoke the cookie, and then you can redirect back to the client.
> 
> ```
> [HttpGet]
>         public async Task<IActionResult> Logout(string logoutId)
>         {
>             await _signInManager.SignOutAsync();
>             return Redirect("http//:localhost:4200");
>         }
> ```
> 
> Instead of hardcoding the url of the client you can also use the PostLogoutRedirectUri that is passed by the client's call issued by signoutRedirect().
> To access this parameter on the server, you can do the following:
> 
> `var context = await _interaction.GetLogoutContextAsync(logoutId); return Redirect(context.PostLogoutRedirectUri); `
> ... where _interaction is a IIdentityServerInteractionService.

This is not correct solution, what's the meaning of using MVC controller action in angular app? So you can't logout when you run your angular app using 'ng serve', because that time controller will not listen your logout call.

**Comment by itorian** [comment]
I had similar issue and to fix this you don't need .net core assemblies (check my above comment), here's the resolution https://github.com/IdentityServer/IdentityServer4/issues/3854

**Comment by mmacneil** [comment]
All fixed as of https://github.com/mmacneil/AngularASPNETCoreOAuth/commit/64452e0130e5f14df03d3e3e01a814fa7df4d3ff

Thanks so much, @nkaenzig and @itorian for the feedback!
