### ISSUE TITLE
Security Concerns 

### ISSUE THREAD

**Issue by Funnyman420** [mmacneil/AngularASPNETCoreOAuth#21]
I'm seeing that you're inserting the Connection String of the database as string and not going with the configuration way (in the PersistedGrantDbContextFactory). Don't you think that that's a security concern?

**Comment by mmacneil** [comment]
Hi @Funnyman420  - can you show me the specific snippet you see this and/or please feel free to submit a PR with an improved approach. :)

**Comment by Funnyman420** [comment]
![image](https://user-images.githubusercontent.com/38563912/91560903-4e106780-e943-11ea-88d5-4cae7a377d68.png)

I'm currently working on, what I think. is a better solution. If I come up with anything, I'll let you know!

**Comment by mmacneil** [comment]
I remember this, as I was preparing the demo I couldn't easily find a method to access the `appsettings` to read the conn string from there - hence the hard coding.

But, you're totally right, for a production system that is a terrible practice! Please pass along a better method if you find it.
